version: '3.7'

services:
  redis-master:
    container_name: redis_master
    image: redis:7
    ports:
      - "6379:6379"
 
  redis-slave-1:
    container_name: redis_slave_1
    image: redis:7
    command: redis-server --slaveof redis-master 6379 --port 6380
    links:
      - redis-master
    ports:
      - "6380:6380"
 
  redis-slave-2:
    container_name: redis_slave_2
    image: redis:7
    command: redis-server --slaveof redis-master 6379 --port 6381
    links:
      - redis-master
    ports:
      - "6381:6381"
     
  redis-sentinel-1:
    container_name: redis_sentinel_1
    build: 
      context: ./redis-sentinel
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    links:
      - redis-master
    ports:
      - "26379:26379" 
    environment:
      - SENTINEL_PORT=26379

  redis-sentinel-2:
    container_name: redis_sentinel_2
    build: 
      context: ./redis-sentinel
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    links:
      - redis-master
    ports:
      - "26380:26380"
    environment:
      - SENTINEL_PORT=26380

  redis-sentinel-3:
    container_name: redis_sentinel_3
    build: 
      context: ./redis-sentinel
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    links:
      - redis-master
    ports:
      - "26381:26381"
    environment:
      - SENTINEL_PORT=26381
