version: '3.7'

services:
  redis-master:
    container_name: redis_master
    image: redis:7
    network_mode: host

  redis-slave-1:
    container_name: redis_slave_1
    image: redis:7
    command: redis-server --slaveof localhost 6379 --port 6380
    network_mode: host
 
  redis-slave-2:
    container_name: redis_slave_2
    image: redis:7
    command: redis-server --slaveof 127.0.0.1 6379 --port 6381
    network_mode: host

  redis-sentinel-1:
    container_name: redis_sentinel_1
    build: 
      context: ./redis-sentinel
    network_mode: host
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    environment:
      - SENTINEL_PORT=26379

  redis-sentinel-2:
    container_name: redis_sentinel_2
    build: 
      context: ./redis-sentinel
    network_mode: host
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    environment:
      - SENTINEL_PORT=26380

  redis-sentinel-3:
    container_name: redis_sentinel_3
    build: 
      context: ./redis-sentinel
    network_mode: host
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    environment:
      - SENTINEL_PORT=26381
